In [1]:
import numpy as np

In [2]:
# array() Function creates an array.
# numpy array is different from python lists as numpy array contains same data-type items.
# In this array only integers are allowed.
integerArray = np.array([1,2,3,4], int)

In [3]:
print(integerArray)

[1 2 3 4]


In [4]:
# type of integerArray
print(type(integerArray))

<class 'numpy.ndarray'>


In [5]:
#Accessing elements is just like normal arrays.
print(integerArray[0])

1


In [6]:
print(integerArray[45])

IndexError: index 45 is out of bounds for axis 0 with size 4

In [9]:
# Accessing range values.
# Syntax
# array[start:end:steps]
print(integerArray[0:2])

[1 2]


In [10]:
print(integerArray[0:4:2])

[1 3]


In [11]:
# Iterating over numpy array.
i = 0
while i < len(integerArray):
    print(integerArray[i])
    i = i + 2

1
3


In [12]:
# Iterating over numpy array using for loop.
for item in integerArray:
    print(item)

1
2
3
4


# Can you reverse the integerArray using ranges???

In [16]:
print(integerArray[::-1])

[4 3 2 1]


# Different type of array with numpy

In [25]:
# Array of zeros 
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
# Array of ones of datatype int 
print(np.ones(10, dtype=int))

[1 1 1 1 1 1 1 1 1 1]


In [27]:
# Range of numbers
rangeArray = np.array(range(10), int)
print(rangeArray)

[0 1 2 3 4 5 6 7 8 9]


In [34]:
newRange = np.array(range(100),int)
newRange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [37]:
# resize function for resizing any  array
newRange.reshape(20,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

# Multi Dimensional Array with Numpy

In [39]:
# 2D array can be created like ..
floatArray = np.array([[1,2,3], [4,5,6]], float)
print(floatArray)

[[1. 2. 3.]
 [4. 5. 6.]]


In [41]:
# we can resize 2d array toooo
floatArray.resize(3,2)
print(floatArray)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [42]:
# Convert multidimensional to one dimensional array
floatArray = floatArray.flatten()
floatArray

array([1., 2., 3., 4., 5., 6.])

In [43]:
arr1 = np.array([[1,2], [3,4]], int)
arr2 = np.array([[5,6], [7,8]], int)
print(np.concatenate((arr1, arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [44]:
np.concatenate((arr1, arr2), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [45]:
np.concatenate((arr1, arr2) , axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [46]:
print(arr1)
print(arr2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [48]:
# Element wise addition 
arr1+arr2

array([[ 6,  8],
       [10, 12]])

In [49]:
# Element wise multiplication
arr1*arr2

array([[ 5, 12],
       [21, 32]])

In [51]:
arr1+2
# It add 2 to all the elements of the array arr1

array([[3, 4],
       [5, 6]])

In [58]:
# similarly we can perform element wise operations on any array
print(arr1 / 5)
print("-----")
print(arr1 + 10)
print("----------")
print(arr1 * 5)

[[0.2 0.4]
 [0.6 0.8]]
-----
[[11 12]
 [13 14]]
----------
[[ 5 10]
 [15 20]]


In [61]:
print(arr1 ** 2) # It does element wise square to all element ..

[[ 1  4]
 [ 9 16]]


In [63]:
print(arr1.sum())

10


In [68]:
print(arr1)

[[1 2]
 [3 4]]


In [69]:
# Axis wise operations 
# Axis 1 means along Rows 
# Axis 0 means along Column
print(arr1.sum(axis = 1))
print(arr1.sum(axis = 0))

[3 7]
[4 6]


In [70]:
print(arr1.max(axis = 1))

[2 4]


In [72]:
print(arr1.min(axis = 0))

[1 2]


In [73]:
print(arr1.mean(axis = 0))

[2. 3.]


In [75]:
# Get diagonal value ..
arr1.diagonal()

array([1, 4])

In [107]:
ar = np.array([1,2],int)
ar.diagonal()

ValueError: diag requires an array of at least two dimensions

In [78]:
new_arr = np.ones((5,5) , dtype = int)
new_arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [80]:
new_arr = np.zeros((5,5),int)
print(new_arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [86]:
#we can create Identity matrix using eye function 
new_arr = np.eye(5,5)
print(new_arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [88]:
new_arr.diagonal()

array([1., 1., 1., 1., 1.])

In [108]:
print(arr1)

[[1 2]
 [3 4]]


In [89]:
# we can do element wise comparision ..
arr1 > 10

array([[False, False],
       [False, False]])

In [90]:
print(arr1)

[[1 2]
 [3 4]]


In [91]:
print(arr2)

[[5 6]
 [7 8]]


In [92]:
arr1>arr2

array([[False, False],
       [False, False]])

In [94]:
# Dot product of two matrix using dot function
mat = np.dot(arr1, arr2)
print(mat)

[[19 22]
 [43 50]]


# Random arrays

In [96]:
r_array = np.random.rand(5)
print(r_array)

[0.11544788 0.16882328 0.7080051  0.97586065 0.21364738]


In [99]:
r_array = np.random.rand(3,3)
print(r_array)

[[0.5931212  0.0821853  0.55443776]
 [0.31182357 0.59023036 0.24147084]
 [0.38549531 0.28593678 0.66401579]]


In [106]:
# Randint for creating array with integer element 
r_array = np.random.randint(1,10,(5,5))  # It create random integer lies between 1 to 10 .
print(r_array)

[[9 1 9 5 4]
 [8 9 2 4 3]
 [1 9 4 6 7]
 [9 5 6 9 9]
 [6 5 9 7 5]]


In [110]:
r1 = np.random.randint(10,100,(50,50))
r2 = np.random.randint(1,100,(50,50))
print(r1)
print(r2)

[[47 58 77 ... 65 45 26]
 [51 69 98 ... 90 52 75]
 [60 53 32 ... 59 65 11]
 ...
 [55 77 84 ... 88 85 35]
 [31 31 69 ... 57 99 17]
 [64 74 89 ... 46 62 56]]
[[34 96 39 ...  7 36 97]
 [66 48  1 ... 76 37 43]
 [78 38  8 ... 58 68 17]
 ...
 [49 47  6 ... 47 82 22]
 [72 92 85 ... 12 21 92]
 [38 98 44 ... 21 61  2]]


In [122]:
result = np.dot(r1,r2)

In [123]:
print(result)

[[127923 149007 116690 ... 122159 135435 138399]
 [135560 166429 134136 ... 123496 143395 150325]
 [113086 136216 104443 ... 107075 129334 130264]
 ...
 [139238 162314 126605 ... 129030 148310 151257]
 [117620 154044 116145 ... 114679 122792 133407]
 [154601 181224 130477 ... 132752 161916 160496]]


In [125]:
print(result.size)

2500


In [126]:
print(result.shape)

(50, 50)
